test_place_ge_ad(
  361_391,
  place_ge_id: 361_391,
  link: "http://place.ge/en/ads/view/361391",
  publication_date: Date.new(2015, 9, 29),
  deal_type: 'to_buy',
  property_type: 'flat',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 1,
  region: 'Vake-Saburtalo',
  district_id: 18,
  district: 'Saburtalo',
  street_id: 115,
  street: 'Vazha-pshavela ave.',
  is_urgent: true,
  price: '32500',
  price_per_area_unit: nil,
  price_currency: 'dollar',
  price_timeframe: nil,
  area: '55',
  area_unit: 'sq. m.',
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'Partially white frame',
  project: 'Czech',
  status: 'new building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Vake-Saburtalo, Saburtalo, Vazha-pshavela ave.',
  floor_number: '3',
  total_floor_count: '9',
  room_count: '2',
  bathroom_count: '2',
  bedroom_count: '2',
  balcony_count: '1',
  features: 'Loggia, Storeroom, Dressing room, Heating, Hot water, Television, Internet.',
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: true,
  has_wardrobe: true,
  has_air_conditioning: false,
  has_heating: true,
  has_loggia: true,
  has_appliances: false,
  has_hot_water: true,
  has_tv: true,
  has_phone: false,
  has_internet: true,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'შევიძენ ორ ოთახიანს საბურთალოს რაიონში,ან გავცვლი ჩემს ერთ ოთახიან კარგად გარემონტებულ ბინას მდებარეს ამავე რაიონში-ვაჟა/ფშაველაზე,ქავთარაძეზე ან ნუცუბიძის ქუჩაზე ახალ აშენებულ დამთავრებულ კორპუსში თეთრი კარკასით ან დასრულებული რემონტით თანხის დამატებით.მობ/599490122 ან 571 51 34 51,599190244',
  telephone_number: '5-99-490122',
  seller_type: nil,
  seller_name: nil
)
