test_place_ge_ad(
  468_513,
  place_ge_id: 468_513,
  link: 'http://place.ge/en/ads/view/468513',
  publication_date: Date.new(2015, 9, 16),
  deal_type: 'for_rent',
  property_type: 'private_house',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 4,
  region: 'Didube-Chugureti',
  district_id: 48,
  district: 'Chugureti',
  street_id: nil,
  street: nil,
  is_urgent: false,
  price: '500',
  price_per_area_unit: '4',
  price_currency: 'dollar',
  price_timeframe: 'month',
  area: '136',
  area_unit: 'sq. m.',
  land_area: '411',
  land_area_unit: 'sq. m.',
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'Renovated',
  project: nil,
  status: nil,
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Didube-Chugureti, Chugureti, ჭყონდიდელი',
  floor_number: nil,
  total_floor_count: '1',
  room_count: '5',
  bathroom_count: '2',
  bedroom_count: '4',
  balcony_count: '1',
  features: 'Garage / Parking, Storeroom, Dressing room, Furniture, Heating, Hot water, Television, Internet, Porch.',
  is_bank_real_estate: false,
  has_garage_or_parking: true,
  has_lift: false,
  has_furniture: true,
  has_fireplace: false,
  has_storage_area: true,
  has_wardrobe: true,
  has_air_conditioning: false,
  has_heating: true,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: true,
  has_tv: true,
  has_phone: false,
  has_internet: true,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: true,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'ქირავდება კერძო სახლი, გამწვანებული ეზოთი,52 მეტრი სარდაფით. მეტრო ნაძალავებიდან 5 წუთი ფეხით 591093081 მინიმალური ავეჯით',
  telephone_number: '5-91-093081',
  seller_type: nil,
  seller_name: nil
)
