test_place_ge_ad(
  181038,
  place_ge_id: 181038,
  link: "http://place.ge/en/ads/view/#{181038}",
  publication_date: Date.new(2015, 7, 31),
  deal_type: 'for_sale',
  property_type: 'commercial_estate',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 6,
  region: 'Old Tbilisi',
  district_id: 65,
  district: 'Krtsanisi',
  street_id: nil,
  street: nil,
  is_urgent: false,
  price: '1900000',
  price_per_area_unit: '1267',
  price_currency: 'dollar',
  price_timeframe: nil,
  area: '1500',
  area_unit: 'sq. m.',
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'Black Frame',
  project: nil,
  status: 'new building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Old Tbilisi, Krtsanisi',
  floor_number: '4',
  total_floor_count: '4',
  room_count: '20',
  bathroom_count: '7',
  bedroom_count: nil,
  balcony_count: '8',
  features: 'Garage / Parking, Conference hall, Stained-glass windows.',
  is_bank_real_estate: false,
  has_garage_or_parking: true,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: true,
  has_stained_glass_windows: true,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'magaria s a e l h o s t v i s ......fasi 1900000$ tel 2519411 577445907',
  telephone_number: '5-96-050404',
  seller_type: 'Agency  ',
  seller_name: 'ოქროს გასაღები'
)
