test_place_ge_ad(
  252_686,
  place_ge_id: 252_686,
  link: 'http://place.ge/en/ads/view/252686',
  publication_date: Date.new(2015, 9, 14),
  deal_type: 'for_rent',
  property_type: 'land',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 1,
  region: 'Vake-Saburtalo',
  district_id: 18,
  district: 'Saburtalo',
  street_id: nil,
  street: nil,
  is_urgent: true,
  price: '79000',
  price_per_area_unit: '293',
  price_currency: 'dollar',
  price_timeframe: 'month',
  area: nil,
  area_unit: nil,
  land_area: '270',
  land_area_unit: 'sq. m.',
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: 'Non Agricultural',
  condition: nil,
  project: nil,
  status: nil,
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Vake-Saburtalo, Saburtalo',
  floor_number: nil,
  total_floor_count: nil,
  room_count: nil,
  bathroom_count: nil,
  bedroom_count: nil,
  balcony_count: nil,
  features: 'Electricity, Gas, Water supply.',
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: true,
  has_gas: true,
  has_water_supply: true,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'სასწრაფოდ! იყიდება მიწის ნაკვეთი ქავთარაძის და ვაჟა-ფშაველას დამაკავშირებელ ქუჩაზე. გზის pირას. 270 კვ. მ. ფასი: 79 000 $',
  telephone_number: '571962444',
  seller_type: 'Agency',
  seller_name: 'dreamhouse'
)
