test_place_ge_ad(
  267_846,
  place_ge_id: 267_846,
  link: "http://place.ge/en/ads/view/#{267_846}",
  publication_date: Date.new(2015, 6, 22),
  deal_type: 'for_rent',
  property_type: 'flat',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 1,
  region: 'Vake-Saburtalo',
  district_id: 2,
  district: 'Vake',
  street_id: 47,
  street: 'N. Djvania st.',
  is_urgent: true,
  price: '1050',
  price_per_area_unit: '11',
  price_currency: 'dollar',
  price_timeframe: 'month',
  area: '93',
  area_unit: 'sq. m.',
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'Newly renovated',
  project: 'Moscow',
  status: 'new building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: '28',
  apartment_number: nil,
  address: 'Tbilisi, Vake-Saburtalo, Vake, N. Djvania st.',
  floor_number: '6',
  total_floor_count: '7',
  room_count: '2',
  bathroom_count: '1',
  bedroom_count: '1',
  balcony_count: nil,
  features: 'Garage / Parking, Appliances, Air conditioning, Heating, Hot water, Television, Telephone, Internet, Doorphone, Guard, Elevator.',
  is_bank_real_estate: false,
  has_garage_or_parking: true,
  has_lift: true,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: true,
  has_heating: true,
  has_loggia: false,
  has_appliances: true,
  has_hot_water: true,
  has_tv: true,
  has_phone: true,
  has_internet: true,
  has_alarm: false,
  has_doorphone: true,
  has_security: true,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'Новая квартира в эко-комплексе "Тбилисия". В квартире сделан евро-ремонт. Вся техника и сантехника новая. Сантехника испанская фирма ROCA, техника фирма BOSH Подробнее на www.tbilisia.ru/ge',
  telephone_number: '599076763, 599070026',
  seller_type: 'Company',
  seller_name: 'THECO limited'
)
