test_place_ge_ad(
  318_025,
  place_ge_id: 318_025,
  link: 'http://place.ge/en/ads/view/318025',
  publication_date: Date.new(2016, 2, 29),
  deal_type: 'for_rent',
  property_type: 'summer_house',
  city_id: 1,
  city: 'Tbilisi',
  region_id: nil,
  region: nil,
  district_id: nil,
  district: nil,
  street_id: nil,
  street: nil,
  is_urgent: false,
  price: '5000',
  price_per_area_unit: '9',
  price_currency: 'dollar',
  price_timeframe: 'month',
  area: '543',
  area_unit: 'sq. m.',
  land_area: '543',
  land_area_unit: 'sq. m.',
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'Eurostandard',
  project: nil,
  status: 'old building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi',
  floor_number: nil,
  total_floor_count: '3',
  room_count: '7',
  bathroom_count: '2',
  bedroom_count: '6',
  balcony_count: '1',
  features: 'Garage / Parking, Furniture, Appliances, Porch, Mansard.',
  is_bank_real_estate: false,
  has_garage_or_parking: true,
  has_lift: false,
  has_furniture: true,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: true,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: true,
  is_mansard: true,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'ShindisiÂÂ, yvelanairad mocyobili, baseini, tenisis magida, biliardi, sezoni 5000$',
  telephone_number: '593303086',
  seller_type: nil,
  seller_name: nil
)
