test_place_ge_ad(325646, {
  place_ge_id: 325646,
  link: "http://place.ge/en/ads/view/325646",
  publication_date: Date.new(2015, 9, 16),
  deal_type: 'for_sale',
  property_type: 'summer_house',
  city_id: 29,
  city: 'Bazaleti',
  region_id: nil,
  region: nil,
  district_id: nil,
  district: nil,
  street_id: nil,
  street: nil,
  is_urgent: false,
  price: 'Contract price',
  price_per_area_unit: nil,
  price_currency: nil,
  price_timeframe: nil,
  area: '363',
  area_unit: 'sq. m.',
  land_area: '1000',
  land_area_unit: 'sq. m.',
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'White Frame',
  project: nil,
  status: nil,
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Bazaleti',
  floor_number: nil,
  total_floor_count: '3',
  room_count: '8',
  bathroom_count: '3',
  bedroom_count: '4',
  balcony_count: '2',
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_showcase: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'იყიდება 2 სართულიანი აგარაკი ბელეტაჟზე, მანსარდით. ნახევარსარდაფი თავისი ფანჯრებით (შავი კარკასი), I სართული ტერასით თეთრი კარკასი, ელ. გაყვანილობით და მანსარდი ტერასით (შავი კარკასი). სამივე სართულზე გათვლილია ფართი სველი წერტილებისთვის. ცინკის სახურავით, ყველა ფანჯარაზე რკ.გისოსებით, რკ/კარით. სახლი აშენებულია 11X11, თითო სართულის ფართი 121 კვმ. 1000კვმ ხეხილიანი ეზო კაპიტალურად შემოღობილი, ფანტასტიური ხედებით, ბაზალეთის ტბიდან ზუსტად 3 კმ-ის მოშორებით. ფასი: შეთანხმებით მის: დუშეთი, სოფ. მილახვრიანთკარი. ტელ: 2 148 145; 599 06 67 87',
  telephone_number: '5-97-003886',
  seller_type: 'Agency',
  seller_name: 'LIDERY'
})
