test_place_ge_ad(338099, {
  place_ge_id: 338099,
  link: "http://place.ge/en/ads/view/338099",
  publication_date: Date.new(2015, 9, 21),
  deal_type: 'for_rent',
  property_type: 'commercial_estate',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 1,
  region: 'Vake-Saburtalo',
  district_id: 2,
  district: 'Vake',
  street_id: 20,
  street: 'Abuladze st.',
  is_urgent: false,
  price: '500',
  price_per_area_unit: '14',
  price_currency: 'dollar',
  price_timeframe: 'month',
  area: '35',
  area_unit: 'sq. m.',
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: nil,
  project: nil,
  status: nil,
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Vake-Saburtalo, Vake, Abuladze st.',
  floor_number: nil,
  total_floor_count: '1',
  room_count: nil,
  bathroom_count: '1',
  bedroom_count: nil,
  balcony_count: nil,
  features: 'Heating, Hot water.',
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: true,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: true,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_showcase: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'ქირავდება საოფისე ფართი ვაკეში, აბულაძის ქუჩაზე. ფასი: 500$ (ფასში შედის საშემოსავლო). ტელ. 598 45 19 41',
  telephone_number: '5-98-451941',
  seller_type: 'Agency',
  seller_name: 'Realtis'
})
