test_place_ge_ad(355198, {
  place_ge_id: 355198,
  link: "http://place.ge/en/ads/view/355198",
  publication_date: Date.new(2015, 6, 2),
  deal_type: 'for_sale',
  property_type: 'private_house',
  city_id: 43,
  city: 'Gori',
  region_id: nil,
  region: nil,
  district_id: nil,
  district: nil,
  street_id: nil,
  street: nil,
  is_urgent: false,
  price: '58000',
  price_per_area_unit: '112',
  price_currency: 'dollar',
  price_timeframe: nil,
  area: '517',
  area_unit: 'sq. m.',
  land_area: '383',
  land_area_unit: 'sq. m.',
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'Old renovated',
  project: nil,
  status: nil,
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: 'გმირების ქუჩა #28',
  apartment_number: nil,
  address: 'Gori',
  floor_number: nil,
  total_floor_count: '2',
  room_count: '5',
  bathroom_count: '1',
  bedroom_count: '3',
  balcony_count: nil,
  features: 'Banking Real Estate.',
  is_bank_real_estate: true,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_showcase: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'იყიდება კერძო სახლი გორში მიწა 517 კვ.მ. შენობა 383 კვ.მ. გმირების ქუჩაზე 400 კვმ. ფასი 58000$ დაუკავშირდით 599553233 მერაბი',
  telephone_number: '5-95-113932',
  seller_type: 'Bank',
  seller_name: nil
})
