test_place_ge_ad(
  396821,
  place_ge_id: 396821,
  link: "http://place.ge/en/ads/view/396821",
  publication_date: Date.new(2016, 5, 28),
  deal_type: 'to_buy',
  property_type: 'land',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 1,
  region: 'Vake-Saburtalo',
  district_id: 13,
  district: 'Didi digomi',
  street_id: nil,
  street: nil,
  is_urgent: true,
  price: '35',
  price_per_area_unit: nil,
  price_currency: 'dollar',
  price_timeframe: nil,
  area: nil,
  area_unit: nil,
  land_area: '700',
  land_area_unit: 'sq. m.',
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: nil,
  project: nil,
  status: nil,
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Vake-Saburtalo, Didi digomi',
  floor_number: nil,
  total_floor_count: nil,
  room_count: nil,
  bathroom_count: nil,
  bedroom_count: nil,
  balcony_count: nil,
  features: 'Electricity, Gas, Water supply, Sewage, Building.',
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: true,
  has_gas: true,
  has_water_supply: true,
  has_sewage: true,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'ვეძებ დიდი დიღმის ტერიტორიაზე ,ან ტოიოტა ცენტრის უკან 800 კვადრატულ მიწის ნაკვეთს 30-40 დოლარის ფარგლებში, მაკერები არ გამომეხმაუროთ.557226428',
  telephone_number: '557226428',
  seller_type: 'Agency',
  seller_name: 'მიწის ნაკვეთის ყიდვა გაყიდვა'
)
