test_place_ge_ad(
  404_046,
  place_ge_id: 404_046,
  link: 'http://place.ge/en/ads/view/404046',
  publication_date: Date.new(2016, 4, 19),
  deal_type: 'for_sale',
  property_type: 'summer_house',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 6,
  region: 'Old Tbilisi',
  district_id: 66,
  district: 'Mtatsminda',
  street_id: 1146,
  street: 'Shindisi st.',
  is_urgent: false,
  price: '115000',
  price_per_area_unit: '548',
  price_currency: 'dollar',
  price_timeframe: nil,
  area: '210',
  area_unit: 'sq. m.',
  land_area: '900',
  land_area_unit: 'sq. m.',
  distance_from_tbilisi: '9',
  distance_from_main_road: '200m',
  function: nil,
  condition: 'Newly renovated',
  project: nil,
  status: 'new building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Old Tbilisi, Mtatsminda, Shindisi st.',
  floor_number: nil,
  total_floor_count: '2',
  room_count: '8',
  bathroom_count: '1',
  bedroom_count: '5',
  balcony_count: '1',
  features: 'Garage / Parking, Storeroom, Dressing room.',
  is_bank_real_estate: false,
  has_garage_or_parking: true,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: true,
  has_wardrobe: true,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'ლამაზად ცხოვრება!ადვილად მისასვლელი! შინდისი, 9კმ თავისუფლების მოედნიდან.ხედი თბილისზე,არაჩვეულებრივი ბუნება',
  telephone_number: '579068764',
  seller_type: 'Agency',
  seller_name: 'Mileni'
)
