test_place_ge_ad(
  410_181,
  place_ge_id: 410_181,
  link: 'http://place.ge/en/ads/view/410181',
  publication_date: Date.new(2016, 6, 13),
  deal_type: 'for_sale',
  property_type: 'summer_house',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 3,
  region: 'Didgori',
  district_id: 42,
  district: 'Tskneti',
  street_id: nil,
  street: nil,
  is_urgent: false,
  price: '188000',
  price_per_area_unit: '627',
  price_currency: 'dollar',
  price_timeframe: nil,
  area: '300',
  area_unit: 'sq. m.',
  land_area: '800',
  land_area_unit: 'sq. m.',
  distance_from_tbilisi: '4',
  distance_from_main_road: nil,
  function: nil,
  condition: 'Renovated',
  project: nil,
  status: 'new building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Didgori, Tskneti',
  floor_number: nil,
  total_floor_count: '2',
  room_count: '5',
  bathroom_count: '3',
  bedroom_count: '4',
  balcony_count: '1',
  features: 'Storeroom, Dressing room, Hot water, Television, Internet, Porch.',
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: true,
  has_wardrobe: true,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: true,
  has_tv: true,
  has_phone: false,
  has_internet: true,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: true,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: '800 მ² - 199000 $ რატომ უნდა გადაიხადო ქირაში? 300 კვ.მ. 4 საძინებელი, კაბინეტი, მისაღები რომელიც გეუბნება ,,კეთილი იყოს თქვენი მობრძანება!", დიდი სამზარეულო, ორი ბუხარი, 3 სველი წერტილი, შესანიშნავი ბალახის გაზონი, აივანი. საცურაო აუზი. წყნეთი, გამგეობასთან',
  telephone_number: '579068764',
  seller_type: 'Agency',
  seller_name: 'Mileni'
)
