test_place_ge_ad(442_304,   place_ge_id: 442_304,
                            link: 'http://place.ge/en/ads/view/442304',
                            publication_date: Date.new(2015, 7, 10),
                            deal_type: 'for_sale',
                            property_type: 'flat',
                            city_id: 1,
                            city: 'Tbilisi',
                            region_id: 1,
                            region: 'Vake-Saburtalo',
                            district_id: 18,
                            district: 'Saburtalo',
                            street_id: 203,
                            street: 'Shartava st.',
                            is_urgent: true,
                            price: '45750',
                            price_per_area_unit: '750',
                            price_currency: 'dollar',
                            price_timeframe: nil,
                            area: '61',
                            area_unit: 'sq. m.',
                            land_area: nil,
                            land_area_unit: nil,
                            distance_from_tbilisi: nil,
                            distance_from_main_road: nil,
                            function: nil,
                            condition: 'White Frame',
                            project: nil,
                            status: 'under construction',
                            array: nil,
                            quarter: nil,
                            neighborhood: nil,
                            building_number: nil,
                            apartment_number: nil,
                            address: 'Tbilisi, Vake-Saburtalo, Saburtalo, Shartava st.',
                            floor_number: '5',
                            total_floor_count: '10',
                            room_count: '2',
                            bathroom_count: '1',
                            bedroom_count: '1',
                            balcony_count: '1',
                            features: 'Elevator.',
                            is_bank_real_estate: false,
                            has_garage_or_parking: false,
                            has_lift: true,
                            has_furniture: false,
                            has_fireplace: false,
                            has_storage_area: false,
                            has_wardrobe: false,
                            has_air_conditioning: false,
                            has_heating: false,
                            has_loggia: false,
                            has_appliances: false,
                            has_hot_water: false,
                            has_tv: false,
                            has_phone: false,
                            has_internet: false,
                            has_alarm: false,
                            has_doorphone: false,
                            has_security: false,
                            has_conference_hall: false,
                            has_showcase: false,
                            has_veranda: false,
                            is_mansard: false,
                            has_electricity: false,
                            has_gas: false,
                            has_water_supply: false,
                            has_sewage: false,
                            has_inventory: false,
                            has_network: false,
                            has_generator: false,
                            additional_information: 'იყიდება 61 კვ.მ–ის ბინა საბურთალოზე, შარტავას ქუჩაზე, მშენებარე კორპუსში, თეთრი კარკასის მდგომარეობაში, მშენებლობა ჩაბარდება 2016 წლის დეკემბერში , ტელ: 597799292 ია, www.geos.ge',
                            telephone_number: '5-97-799292',
                            seller_type: 'Agency',
                            seller_name: 'GEOS')
