test_place_ge_ad(
  456046,
  place_ge_id: 456046,
  link: "http://place.ge/en/ads/view/#{456046}",
  publication_date: Date.new(2015, 11, 4),
  deal_type: 'to_buy',
  property_type: 'land',
  city_id: 1,
  city: 'Tbilisi',
  region_id: nil,
  region: nil,
  district_id: nil,
  district: nil,
  street_id: nil,
  street: nil,
  is_urgent: true,
  price: nil,
  price_per_area_unit: nil,
  price_currency: nil,
  price_timeframe: nil,
  area: nil,
  area_unit: nil,
  land_area: '100 - 150',
  land_area_unit: 'sq. m.',
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: nil,
  project: nil,
  status: nil,
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi',
  floor_number: nil,
  total_floor_count: nil,
  room_count: nil,
  bathroom_count: nil,
  bedroom_count: nil,
  balcony_count: nil,
  features: nil,
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'შევიძენ 100-150კვ.მ მიწის ნაკვეთს ავტოსამრეცხაოსთვის',
  telephone_number: '5-77-137770',
  seller_type: nil,
  seller_name: nil
)
