test_place_ge_ad(459002, {
  place_ge_id: 459002,
  link: 'http://place.ge/en/ads/view/459002',
  publication_date: Date.new(2015, 9, 3),
  deal_type: 'for_sale',
  property_type: 'flat',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 1,
  region: 'Vake-Saburtalo',
  district_id: 18,
  district: 'Saburtalo',
  street_id: 153,
  street: 'Kavtaradze st.',
  price: '45000',
  price_per_area_unit: '804',
  price_currency: 'dollar',
  price_timeframe: nil,
  area: '56',
  area_unit: 'sq. m.',
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  condition: 'Old renovated',
  project: 'Khrushchev',
  status: 'old building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: '13',
  apartment_number: '6',
  address: 'Tbilisi, Vake-Saburtalo, Saburtalo, Kavtaradze st.',
  floor_number: '2',
  total_floor_count: '5',
  room_count: '2',
  bathroom_count: '1',
  bedroom_count: '1',
  balcony_count: nil,
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: true,
  has_loggia: true,
  has_appliances: false,
  has_hot_water: true,
  has_tv: true,
  has_phone: true,
  has_internet: true,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_showcase: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'იყიდება სუფთა, მყუდრო ბინა, გამწვანებულ გარემოში (35-ე საფეხბურთო სკოლასთან), რომელიც არ საჭიროებს რემონტს. აბაზანა და სამზარეულო ახალგარემონტებული. შემოსასვლელში ჩაშენებული კარადით. ნაწილობრივ ავეჯით, რკინის კარით, ჟალუზებით. შესაძლებელია ფასზე შეთანხმებაც.',
  telephone_number: '5-99-155050',
  seller_type: nil,
  seller_name: nil
})
