test_place_ge_ad(
  462_643,
  place_ge_id: 462_643,
  link: 'http://place.ge/en/ads/view/462643',
  publication_date: Date.new(2015, 9, 4),
  deal_type: 'for_rent',
  property_type: 'land',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 2,
  region: 'Gldani-Nadzaladevi',
  district_id: 27,
  district: 'Mukhiani',
  street_id: nil,
  street: nil,
  is_urgent: true,
  price: 'Contract price',
  price_per_area_unit: nil,
  price_currency: nil,
  price_timeframe: nil,
  area: nil,
  area_unit: nil,
  land_area: '850',
  land_area_unit: 'sq. m.',
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: 'Non Agricultural',
  condition: nil,
  project: nil,
  status: nil,
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Gldani-Nadzaladevi, Mukhiani',
  floor_number: nil,
  total_floor_count: nil,
  room_count: nil,
  bathroom_count: nil,
  bedroom_count: nil,
  balcony_count: nil,
  features: 'Electricity, Sewage.',
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_showcase: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: true,
  has_gas: false,
  has_water_supply: false,
  has_sewage: true,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'ქირავდება მიწის ნაკვეთი 800 კვ.მ, მუხიანში პოლიციის პირდაპირ, ამ მიწის ფართზე ჩვენთან შეთანხმებით შეგიძლიათ აწარმოოთ სამშენებლო სამუშაოები,შეიძლება კორბუსი აშენდეს 599561372 სოსო',
  telephone_number: '5-93-392334',
  seller_type: nil,
  seller_name: nil
)
