test_place_ge_ad(
  464_223,
  place_ge_id: 464_223,
  link: 'http://place.ge/en/ads/view/464223',
  publication_date: Date.new(2015, 9, 16),
  deal_type: 'for_rent',
  property_type: 'flat',
  city_id: 3,
  city: 'Batumi',
  region_id: nil,
  region: nil,
  district_id: nil,
  district: nil,
  street_id: nil,
  street: nil,
  is_urgent: true,
  price: '50',
  price_per_area_unit: '1',
  price_currency: 'lari',
  price_timeframe: 'day',
  area: '35',
  area_unit: 'sq. m.',
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'Newly renovated',
  project: 'City',
  status: 'new building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: '114',
  apartment_number: nil,
  address: 'Batumi, gorgiladzis',
  floor_number: '5',
  total_floor_count: '23',
  room_count: '1',
  bathroom_count: '2',
  bedroom_count: '1',
  balcony_count: nil,
  features: 'Storeroom, Dressing room, Furniture, Appliances, Air conditioning, Heating, Hot water, Television, Internet, Elevator.',
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: true,
  has_furniture: true,
  has_fireplace: false,
  has_storage_area: true,
  has_wardrobe: true,
  has_air_conditioning: true,
  has_heating: true,
  has_loggia: false,
  has_appliances: true,
  has_hot_water: true,
  has_tv: true,
  has_phone: false,
  has_internet: true,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'ქირავდება დღიურად ბინები ახალაშენებული 1 ოთახიანი 2ოთახიანი 3ოთახიანი ყველა ნაირი ბინა დაგვიკავშირდით ყველა ბინა არის ზღვასთან სავალი 100 მეტრში დუშკაბინით ზღვის ხედით დამსვენებლებზე, უმაღლესი ხარისხის ევრორემონტით. საუკეთესო პირობებბით, თეთრეულით პირსახოცები ახლოს მდებარეობს: McDonald`s, იუსტიციის სახლი, მოცეკვავე შადრევანი არდაგანის ტბაზე, კაფე, რესტორნები, დასასვენებელი ადგილები.ზღვიდან 100 მეტრში,ახალი ავეჯით,ტექნიკით, სარეცხი მანქანით,კონდიციონერით,Wi-Fi ინტერნეტით, პლაზმური დიდი ტელევიზორით, ,და სხვა ყველა საჭირო ტექნიკით და საოჯახო ნივთებით,1 საძინებლით,სრული კომფორტით. ფასი შეთანხმებით',
  telephone_number: '5-97-580999',
  seller_type: nil,
  seller_name: nil
)
