test_place_ge_ad(
  466_104,
  place_ge_id: 466_104,
  link: 'http://place.ge/en/ads/view/466104',
  publication_date: Date.new(2015, 9, 11),
  deal_type: 'for_rent',
  property_type: 'commercial_estate',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 5,
  region: 'Isani-Samgori',
  district_id: 54,
  district: 'Navtlugi',
  street_id: 840,
  street: 'Enukidze st.',
  is_urgent: true,
  price: 'Contract price',
  price_per_area_unit: nil,
  price_currency: nil,
  price_timeframe: nil,
  area: '2200',
  area_unit: 'sq. m.',
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: nil,
  project: nil,
  status: 'old building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: '6',
  apartment_number: nil,
  address: 'Tbilisi, Isani-Samgori, Navtlugi, Enukidze st.',
  floor_number: nil,
  total_floor_count: nil,
  room_count: nil,
  bathroom_count: nil,
  bedroom_count: nil,
  balcony_count: nil,
  features: nil,
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_showcase: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: '1კვტ–1.7ლ,ყოველ თვე .კვარტალში – 1.3ლ,წლიურად – 1.2ლ წინასწარი გადახდით. სულ 2200კვტ ქირავდება მთლიანად ან ნახევარი არის დენი და წყალი დარეკეთ ამ ნომერზე:555 05 11 55 ,599068509',
  telephone_number: '5-97-333586',
  seller_type: nil,
  seller_name: nil
)
