test_place_ge_ad(
  467_231,
  place_ge_id: 467_231,
  link: "http://place.ge/en/ads/view/467231",
  publication_date: Date.new(2016, 5, 28),
  deal_type: 'to_rent',
  property_type: 'flat',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 5,
  region: 'Isani-Samgori',
  district_id: 51,
  district: 'Isani',
  street_id: nil,
  street: nil,
  is_urgent: true,
  price: '250',
  price_per_area_unit: nil,
  price_currency: 'lari',
  price_timeframe: 'month',
  area: nil,
  area_unit: nil,
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: nil,
  project: nil,
  status: nil,
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Isani-Samgori, Isani',
  floor_number: nil,
  total_floor_count: nil,
  room_count: '2',
  bathroom_count: '1',
  bedroom_count: nil,
  balcony_count: nil,
  features: nil,
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'ვიქირავებ 2 ოთახიან ბინას ,თავისი სველი წერტილებით მოსკოვის პროსპექტზე ან ისანში ოჯახისთვის,თვეში მაქსიმუმ 300 ლარად,557226428',
  telephone_number: '557226428',
  seller_type: 'Agency',
  seller_name: 'მიწის ნაკვეთის ყიდვა გაყიდვა'
)
