test_place_ge_ad(
  476_011,
  place_ge_id: 476_011,
  link: "http://place.ge/en/ads/view/476011",
  publication_date: Date.new(2015, 9, 30),
  deal_type: 'to_buy',
  property_type: 'flat',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 4,
  region: 'Didube-Chugureti',
  district_id: 44,
  district: 'Digomi',
  street_id: 508,
  street: 'E.Mikeladze st.',
  is_urgent: true,
  price: '60000',
  price_per_area_unit: nil,
  price_currency: 'dollar',
  price_timeframe: nil,
  area: '87',
  area_unit: 'sq. m.',
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'Old renovated',
  project: 'Non standard',
  status: nil,
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Didube-Chugureti, Digomi, E.Mikeladze st.',
  floor_number: '11',
  total_floor_count: '16',
  room_count: '4',
  bathroom_count: '1',
  bedroom_count: '3',
  balcony_count: nil,
  features: nil,
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'სასწრაფოდ იყიდება ბინა მე-5 კვარტალში, მე-20 კორპუსში(გეპეის კორპუსი )მე11 სართულზე.ბინა მდებარეობს საუკეთესო ადგილას,ელლიტარულ კორპუსში.',
  telephone_number: '5-74-105665',
  seller_type: nil,
  seller_name: nil
)
