test_place_ge_ad(
  503899,
  place_ge_id: 503899,
  link: "http://place.ge/en/ads/view/503899",
  publication_date: Date.new(2016, 2, 22),
  deal_type: 'for_sale',
  property_type: 'flat',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 6,
  region: 'Old Tbilisi',
  district_id: 63,
  district: 'Vera',
  street_id: 1054,
  street: 'Tarkhnishvili st.',
  is_urgent: true,
  price: '87000',
  price_per_area_unit: '1000',
  price_currency: 'dollar',
  price_timeframe: nil,
  area: '87',
  area_unit: 'sq. m.',
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'White Frame',
  project: 'Non standard',
  status: 'new building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: nil,
  apartment_number: nil,
  address: 'Tbilisi, Old Tbilisi, Vera, Tarkhnishvili st.',
  floor_number: '5',
  total_floor_count: '12',
  room_count: '3',
  bathroom_count: '1',
  bedroom_count: '2',
  balcony_count: nil,
  features: nil,
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: false,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: false,
  has_wardrobe: false,
  has_air_conditioning: false,
  has_heating: false,
  has_loggia: false,
  has_appliances: false,
  has_hot_water: false,
  has_tv: false,
  has_phone: false,
  has_internet: false,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'სასწრაფოდ ვერაზე თარხნიშვილზე იყიდება ახალ აშენებულში 87 კვ თეთრი კარკასი',
  telephone_number: '599516163',
  seller_type: 'Agency',
  seller_name: nil
)
