test_place_ge_ad(
  548037,
  place_ge_id: 548037,
  link: 'http://place.ge/en/ads/view/548037',
  publication_date: Date.new(2016, 3, 22),
  deal_type: 'for_sale',
  property_type: 'flat',
  city_id: 1,
  city: 'Tbilisi',
  region_id: 5,
  region: 'Isani-Samgori',
  district_id: 50,
  district: 'Varketili',
  street_id: 745,
  street: 'Landia st.',
  is_urgent: true,
  price: '39000',
  price_per_area_unit: '390',
  price_currency: 'dollar',
  price_timeframe: nil,
  area: '100',
  area_unit: 'sq. m.',
  land_area: nil,
  land_area_unit: nil,
  distance_from_tbilisi: nil,
  distance_from_main_road: nil,
  function: nil,
  condition: 'Old renovated',
  project: 'Lvov',
  status: 'old building',
  array: nil,
  quarter: nil,
  neighborhood: nil,
  building_number: '23',
  apartment_number: '21',
  address: 'Tbilisi, Isani-Samgori, Varketili, Landia st.',
  floor_number: '2',
  total_floor_count: '9',
  room_count: '4',
  bathroom_count: '2',
  bedroom_count: '3',
  balcony_count: '1',
  features: 'Loggia, Storeroom, Dressing room, Appliances, Heating, Hot water, Television, Internet, Elevator.',
  is_bank_real_estate: false,
  has_garage_or_parking: false,
  has_lift: true,
  has_furniture: false,
  has_fireplace: false,
  has_storage_area: true,
  has_wardrobe: true,
  has_air_conditioning: false,
  has_heating: true,
  has_loggia: true,
  has_appliances: true,
  has_hot_water: true,
  has_tv: true,
  has_phone: false,
  has_internet: true,
  has_alarm: false,
  has_doorphone: false,
  has_security: false,
  has_conference_hall: false,
  has_stained_glass_windows: false,
  has_veranda: false,
  is_mansard: false,
  has_electricity: false,
  has_gas: false,
  has_water_supply: false,
  has_sewage: false,
  has_inventory: false,
  has_network: false,
  has_generator: false,
  additional_information: 'realur myidvels cotas daukleb kargi supta binaa.',
  telephone_number: '5-77-325739',
  seller_type: nil,
  seller_name: nil
)
