class AddOtherDataToRealEstateAds < ActiveRecord::Migration
  def change
    add_column :real_estate_ads, :additional_information, :text
    add_column :real_estate_ads, :address, :string
    add_column :real_estate_ads, :apartment_number, :string
    add_column :real_estate_ads, :area, :string
    add_column :real_estate_ads, :area_unit, :string
    add_column :real_estate_ads, :balcony_count, :string
    add_column :real_estate_ads, :bathroom_count, :string
    add_column :real_estate_ads, :bedroom_count, :string
    add_column :real_estate_ads, :building_number, :string
    add_column :real_estate_ads, :city, :string
    add_column :real_estate_ads, :city_id, :integer
    add_column :real_estate_ads, :condition, :string
    add_column :real_estate_ads, :deal_type, :string
    add_column :real_estate_ads, :district, :string
    add_column :real_estate_ads, :district_id, :integer
    add_column :real_estate_ads, :features, :string
    add_column :real_estate_ads, :floor_number, :string
    add_column :real_estate_ads, :function, :string
    add_column :real_estate_ads, :has_air_conditioning, :boolean
    add_column :real_estate_ads, :has_alarm, :boolean
    add_column :real_estate_ads, :has_appliances, :boolean
    add_column :real_estate_ads, :has_conference_hall, :boolean
    add_column :real_estate_ads, :has_doorphone, :boolean
    add_column :real_estate_ads, :has_electricity, :boolean
    add_column :real_estate_ads, :has_fireplace, :boolean
    add_column :real_estate_ads, :has_furniture, :boolean
    add_column :real_estate_ads, :has_garage_or_parking, :boolean
    add_column :real_estate_ads, :has_gas, :boolean
    add_column :real_estate_ads, :has_generator, :boolean
    add_column :real_estate_ads, :has_heating, :boolean
    add_column :real_estate_ads, :has_hot_water, :boolean
    add_column :real_estate_ads, :has_internet, :boolean
    add_column :real_estate_ads, :has_inventory, :boolean
    add_column :real_estate_ads, :has_lift, :boolean
    add_column :real_estate_ads, :has_loggia, :boolean
    add_column :real_estate_ads, :has_network, :boolean
    add_column :real_estate_ads, :has_phone, :boolean
    add_column :real_estate_ads, :has_security, :boolean
    add_column :real_estate_ads, :has_sewage, :boolean
    add_column :real_estate_ads, :has_showcase, :boolean
    add_column :real_estate_ads, :has_storage_area, :boolean
    add_column :real_estate_ads, :has_tv, :boolean
    add_column :real_estate_ads, :has_veranda, :boolean
    add_column :real_estate_ads, :has_wardrobe, :boolean
    add_column :real_estate_ads, :has_water_supply, :boolean
    add_column :real_estate_ads, :html_copy_path, :string
    add_column :real_estate_ads, :is_bank_real_estate, :boolean
    add_column :real_estate_ads, :is_mansard, :boolean
    add_column :real_estate_ads, :is_urgent, :boolean
    add_column :real_estate_ads, :land_area, :string
    add_column :real_estate_ads, :land_area_unit, :string
    add_column :real_estate_ads, :price, :string
    add_column :real_estate_ads, :price_currency, :string
    add_column :real_estate_ads, :price_per_area_unit, :string
    add_column :real_estate_ads, :price_timeframe, :string
    add_column :real_estate_ads, :project, :string
    add_column :real_estate_ads, :property_type, :string
    add_column :real_estate_ads, :publication_date, :date
    add_column :real_estate_ads, :region, :string
    add_column :real_estate_ads, :region_id, :integer
    add_column :real_estate_ads, :room_count, :string
    add_column :real_estate_ads, :seller_name, :string
    add_column :real_estate_ads, :seller_type, :string
    add_column :real_estate_ads, :status, :string
    add_column :real_estate_ads, :telephone_number, :string
    add_column :real_estate_ads, :time_of_scrape, :time
    add_column :real_estate_ads, :total_floor_count, :string
  end
end
